/**
 * FarmaSim / BioFarma Verde - Banco de Medicamentos (Top 10 Brasil)
 * Tabela de Preços: Farmácia Convencional / Preço Médio
 */

const MEDICAMENTOS_DATA = [
  {
    id: 1,
    slug: "metformina-glifage-xr-500mg",
    nome: "Metformina / Glifage XR",
    dosagem: "500mg",
    apresentacao: "30 comprimidos de liberação prolongada",
    categoria: "Diabetes & Metabolismo",
    preco: 14.90,
    tarja: "Tarja Vermelha (Sob Prescrição)",
    tarjaTipo: "vermelha",
    laboratorio: "Merck / EMS Genéricos",
    principioAtivo: "Cloridrato de Metformina 500mg",
    registroMS: "MS 1.0089.0345.001-9",
    imagem: "images/metformina.jpg",
    descricao: "Líder geral em unidades vendidas no Brasil. Indicado para o tratamento de diabetes mellitus tipo 2 e prevenção de complicações vasculares.",
    indicacao: "Tratamento de diabetes tipo 2 em adultos e crianças a partir de 10 anos, como monoterapia ou associado a outros antidiabéticos orais ou insulina.",
    modoDeUso: "Tomar 1 a 2 comprimidos ao dia durante ou após o jantar, com água, sem mastigar.",
    contraindicacao: "Insuficiência renal grave, cetoacidose diabética, disfunção hepática grave ou consumo excessivo de álcool.",
    avaliacao: 4.9,
    avaliacoesTotal: 580
  },
  {
    id: 2,
    slug: "losartana-potassica-50mg",
    nome: "Losartana Potássica",
    dosagem: "50mg",
    apresentacao: "30 comprimidos revestidos",
    categoria: "Hipertensão & Coração",
    preco: 11.50,
    tarja: "Tarja Vermelha (Sob Prescrição)",
    tarjaTipo: "vermelha",
    laboratorio: "Medley / Eurofarma",
    principioAtivo: "Losartana Potássica 50mg",
    registroMS: "MS 1.0181.0421.002-3",
    imagem: "images/losartana.jpg",
    descricao: "O anti-hipertensivo genérico mais vendido do país. Atua dilatando os vasos sanguíneos e controlando a pressão arterial.",
    indicacao: "Tratamento da hipertensão arterial, insuficiência cardíaca crônica e proteção renal em pacientes diabéticos tipo 2.",
    modoDeUso: "A dose habitual inicial é de 50mg (1 comprimido) uma vez ao dia, pela manhã ou à noite, com ou sem alimentos.",
    contraindicacao: "Hipersensibilidade à losartana, segundo e terceiro trimestres de gravidez e uso concomitante com alisquireno em pacientes diabéticos.",
    avaliacao: 4.8,
    avaliacoesTotal: 640
  },
  {
    id: 3,
    slug: "dipirona-sodica-gotas-500mg",
    nome: "Dipirona Sódica Gotas",
    dosagem: "500mg/ml",
    apresentacao: "Frasco conta-gotas 20ml",
    categoria: "Dores & Febre",
    preco: 8.90,
    tarja: "Venda Livre",
    tarjaTipo: "livre",
    laboratorio: "Neo Química / Sanofi",
    principioAtivo: "Dipirona Monoidratada 500mg/ml",
    registroMS: "MS 1.5584.0092.001-5",
    imagem: "images/dipirona.jpg",
    descricao: "O analgésico e antitérmico mais tradicional e consumido pelos brasileiros para alívio rápido de dores de cabeça e estados febris.",
    indicacao: "Analgésico e antipirético indicado para dores intensas, cefaleias, dores pós-traumáticas e controle térmico de febre.",
    modoDeUso: "Adultos: 20 a 40 gotas em um pouco de água até 4 vezes ao dia. Não exceder a dose recomendada.",
    contraindicacao: "Hipersensibilidade aos derivados pirazolônicos, asma analgésica e porfiria hepática aguda intermitente.",
    avaliacao: 4.9,
    avaliacoesTotal: 820
  },
  {
    id: 4,
    slug: "omeprazol-20mg",
    nome: "Omeprazol",
    dosagem: "20mg",
    apresentacao: "28 cápsulas duras gastro-resistentes",
    categoria: "Estômago & Digestão",
    preco: 19.90,
    tarja: "Tarja Vermelha (Sob Prescrição)",
    tarjaTipo: "vermelha",
    laboratorio: "Teuto / Cimed",
    principioAtivo: "Omeprazol Microgrânulos 20mg",
    registroMS: "MS 1.0370.0210.003-8",
    imagem: "images/omeprazol.jpg",
    descricao: "Campeão nacional de vendas para o tratamento e prevenção de gastrite, esofagite de refluxo e úlceras pépticas.",
    indicacao: "Tratamento de úlceras gástricas e duodenais, refluxo gastroesofágico, azia recorrente e erradicação de H. pylori.",
    modoDeUso: "Tomar 1 cápsula de 20mg pela manhã, em jejum, deglutida inteira com meio copo de água.",
    contraindicacao: "Hipersensibilidade ao omeprazol ou a outros benzimidazóis substituídos.",
    avaliacao: 4.8,
    avaliacoesTotal: 510
  },
  {
    id: 5,
    slug: "hidroclorotiazida-25mg",
    nome: "Hidroclorotiazida",
    dosagem: "25mg",
    apresentacao: "30 comprimidos",
    categoria: "Hipertensão & Diuréticos",
    preco: 6.50,
    tarja: "Tarja Vermelha (Sob Prescrição)",
    tarjaTipo: "vermelha",
    laboratorio: "EMS S/A",
    principioAtivo: "Hidroclorotiazida 25mg",
    registroMS: "MS 1.0235.0560.001-2",
    imagem: "images/hidroclorotiazida.jpg",
    descricao: "Diurético tiazídico muito prescrito no controle contínuo da pressão arterial e combate à retenção de líquidos corporais.",
    indicacao: "Tratamento da hipertensão arterial essencial (isolada ou em associação) e de edemas associados a insuficiência cardíaca leve a moderada.",
    modoDeUso: "1 comprimido (25mg) uma vez ao dia pela manhã para evitar micção noturna frequente.",
    contraindicacao: "Anúria, insuficiência renal severa com depuração de creatinina baixa ou hipopotassemia refratária.",
    avaliacao: 4.7,
    avaliacoesTotal: 390
  },
  {
    id: 6,
    slug: "nimesulida-100mg",
    nome: "Nimesulida",
    dosagem: "100mg",
    apresentacao: "12 comprimidos",
    categoria: "Anti-inflamatórios",
    preco: 15.20,
    tarja: "Tarja Vermelha (Sob Prescrição)",
    tarjaTipo: "vermelha",
    laboratorio: "Aché / Medley",
    principioAtivo: "Nimesulida 100mg",
    registroMS: "MS 1.0573.0112.002-1",
    imagem: "images/nimesulida.jpg",
    descricao: "Anti-inflamatório não esteroide (AINE) consagrado para alívio rápido de dores inflamatórias agudas, dentárias e de garganta.",
    indicacao: "Tratamento sintomático da dor aguda, dismenorreia primária e estados inflamatórios agudos do trato respiratório superior ou osteoarticular.",
    modoDeUso: "Tomar 1 comprimido (100mg) duas vezes ao dia após as refeições, pelo menor tempo clínico necessário.",
    contraindicacao: "Histórico de reações hepáticas graves, úlcera péptica ativa ou insuficiência cardíaca severa.",
    avaliacao: 4.8,
    avaliacoesTotal: 460
  },
  {
    id: 7,
    slug: "tadalafila-5mg-diario",
    nome: "Tadalafila Diário",
    dosagem: "5mg",
    apresentacao: "30 comprimidos revestidos",
    categoria: "Saúde Masculina",
    preco: 42.00,
    tarja: "Tarja Vermelha (Sob Prescrição)",
    tarjaTipo: "vermelha",
    laboratorio: "Eurofarma / Eli Lilly",
    principioAtivo: "Tadalafila Micronizada 5mg",
    registroMS: "MS 1.0043.0811.004-9",
    imagem: "images/tadalafila.jpg",
    descricao: "Medicamento com enorme alta na procura nos últimos anos. Indicado para disfunção erétil e hiperplasia prostática benigna em dosagem diária contínua.",
    indicacao: "Tratamento contínuo da disfunção erétil e dos sinais e sintomas urinários da hiperplasia prostática benigna (HPB).",
    modoDeUso: "Tomar 1 comprimido de 5mg uma vez ao dia, preferencialmente sempre no mesmo horário, com ou sem alimentos.",
    contraindicacao: "Uso concomitante com qualquer forma de nitrato orgânico ou doadores de óxido nítrico, e cardiopatas graves.",
    avaliacao: 4.9,
    avaliacoesTotal: 710
  },
  {
    id: 8,
    slug: "sinvastatina-20mg",
    nome: "Sinvastatina",
    dosagem: "20mg",
    apresentacao: "30 comprimidos revestidos",
    categoria: "Colesterol & Lipídios",
    preco: 18.90,
    tarja: "Tarja Vermelha (Sob Prescrição)",
    tarjaTipo: "vermelha",
    laboratorio: "Sandoz / EMS",
    principioAtivo: "Sinvastatina 20mg",
    registroMS: "MS 1.0047.0319.001-4",
    imagem: "images/sinvastatina.jpg",
    descricao: "Utilizada de forma contínua para o controle e redução do colesterol alto (LDL) e prevenção de eventos cardiovasculares.",
    indicacao: "Hipercolesterolemia primária, dislipidemia mista e redução do risco de infarto do miocárdio em pacientes coronarianos.",
    modoDeUso: "Tomar 1 comprimido (20mg) uma vez ao dia, à noite, com água.",
    contraindicacao: "Doença hepática ativa ou elevações persistentes e inexplicadas das transaminases séricas, gravidez e lactação.",
    avaliacao: 4.7,
    avaliacoesTotal: 340
  },
  {
    id: 9,
    slug: "ibuprofeno-600mg",
    nome: "Ibuprofeno",
    dosagem: "600mg",
    apresentacao: "20 comprimidos revestidos",
    categoria: "Dores & Febre",
    preco: 21.50,
    tarja: "Venda Livre",
    tarjaTipo: "livre",
    laboratorio: "Neo Química / Abbott",
    principioAtivo: "Ibuprofeno 600mg",
    registroMS: "MS 1.5584.0215.003-7",
    imagem: "images/ibuprofeno.jpg",
    descricao: "Anti-inflamatório, analgésico e antitérmico com grande pico de vendas no inverno contra dores musculares, sinusites e febre.",
    indicacao: "Tratamento de febre, dores musculares, artrite, bursite, dor de dente e desconfortos associados a resfriados comuns.",
    modoDeUso: "1 comprimido de 600mg a cada 8 a 12 horas conforme prescrição ou bula, de preferência após as refeições.",
    contraindicacao: "Hipersensibilidade prévia ao ácido acetilsalicílico ou outros AINEs, sangramento digestivo e úlcera ativa.",
    avaliacao: 4.8,
    avaliacoesTotal: 490
  },
  {
    id: 10,
    slug: "simeticona-gotas-75mg",
    nome: "Simeticona Gotas",
    dosagem: "75mg/ml",
    apresentacao: "Frasco conta-gotas com 15ml",
    categoria: "Estômago & Digestão",
    preco: 12.80,
    tarja: "Venda Livre",
    tarjaTipo: "livre",
    laboratorio: "Cimed / Takeda (Luftal)",
    principioAtivo: "Simeticona Emulsão 75mg/ml",
    registroMS: "MS 1.4381.0028.001-0",
    imagem: "images/simeticona.jpg",
    descricao: "Medicamento amplamente vendido para alívio rápido de gases intestinais, distensão e cólicas abdominais.",
    indicacao: "Alívio de flatulência, sensação de estufamento abdominal e preparo intestinal para exames de ultrassonografia ou endoscopia.",
    modoDeUso: "Adultos: 40 a 50 gotas até 3 vezes ao dia após as refeições ou ao deitar. Crianças: conforme orientação pediátrica.",
    contraindicacao: "Distensão abdominal grave sem diagnóstico prévio, suspeita de perfuração ou obstrução intestinal.",
    avaliacao: 4.9,
    avaliacoesTotal: 610
  }
];
