export const termosIgnorados = [
  'cloridrato de',
  'cloridrato',
  'bromidrato de',
  'maleato de',
  'besilato de',
  'succinato de',
  'potassica',
  'potassico',
  'potassio',
  'sodica',
  'sodico',
  'sodio',
  'calcica',
  'magnesica',
  'monoidratada',
  'monoidratado',
  'di-hidratada',
  'tri-hidratada',
  'micronizada',
  'micronizado',
  'microgranulos',
  'emulsao',
  'gotas',
  'xr',
] as const

export const sinonimos: Readonly<Record<string, string>> = {
  metamizol: 'dipirona',
  'metamizol sodico': 'dipirona',
  glifage: 'metformina',
  acetaminofeno: 'paracetamol',
  'dimeticona ativada': 'simeticona',
  'acido acetilsalicilico': 'aas',
  hctz: 'hidroclorotiazida',
}
